In [17]:
import pandas as pd

from dataclasses import dataclass
from typing import List

In [10]:
@dataclass
class Provider:
    id: int
    commission: float
    conversion: float
    min_sum: float
    max_sum: float
    limit_max: float
    limit_min: float
    processing_time: float
    currency: float

    total_amount: int = 0

    def __repr__(self):
        return str(self.__dict__)

In [11]:
payments = pd.read_csv("data/payments_1.csv")

payments.eventTimeRes = pd.to_datetime(payments.eventTimeRes)
payments = payments.sort_values(by="eventTimeRes")


providers = pd.read_csv("data/providers_1.csv")
providers.TIME = pd.to_datetime(providers.TIME)

providers = providers.sort_values(by="TIME")
providers = providers.drop_duplicates(subset=["TIME", "ID"], keep="last")

providers.index = range(len(providers))

currencies = pd.read_csv("data/ex_rates.csv")
currencies = {row["destination"]: row["rate"] for _, row in currencies.iterrows()}

In [12]:
def update_providers(providers: List[Provider]):
    pass


def initialize_provider(row: pd.Series) -> Provider:
    return Provider(id=row.ID, 
                    commission=row.COMMISSION, 
                    conversion=row.CONVERSION, 
                    processing_time=row.AVG_TIME,
                    limit_min=row.LIMIT_MIN,
                    min_sum=row.MIN_SUM,
                    max_sum=row.MAX_SUM,
                    limit_max=row.LIMIT_MAX,
                    currency=row.CURRENCY)

In [6]:
start_time = providers.iloc[0]["TIME"]

In [14]:
provider_objects = []

for _, row in providers[providers.TIME == start_time].iterrows():
    provider_objects.append(initialize_provider(row))

In [19]:
payments.iloc[0]

eventTimeRes                 2024-11-24 21:00:00
amount                                     700.0
cur                                          RUB
payment         c77be33e8db2f5352ebbc0a1b3f10e3e
cardToken       336d5ebc5436534e61d16e63ddfca327
Name: 193977, dtype: object

In [23]:
payments.iloc[2]["eventTimeRes"]

Timestamp('2024-11-24 21:00:01')

In [21]:
providers

,TIME,ID,CONVERSION,AVG_TIME,MIN_SUM,MAX_SUM,LIMIT_MIN,LIMIT_MAX,LIMIT_BY_CARD,COMMISSION,CURRENCY
0,2024-11-24 21:00:00,0,0.50,18.0,700.0,5500.0,61000.0,12900000.0,-,0.035,UZS
1,2024-11-24 21:00:00,26,0.65,26.0,700.0,6000.0,31000.0,18600000.0,-,0.045,MYR
2,2024-11-24 21:00:00,27,0.75,18.0,100.0,4500.0,21000.0,5000000.0,-,0.040,MYR
3,2024-11-24 21:00:00,28,0.65,22.0,200.0,9000.0,61000.0,20900000.0,-,0.045,MYR
4,2024-11-24 21:00:00,29,0.65,14.0,100.0,9000.0,81000.0,14700000.0,-,0.030,USD
...,...,...,...,...,...,...,...,...,...,...,...
446,2024-11-25 21:00:00,2,0.55,8.0,800.0,8000.0,81000.0,16500000.0,-,0.027,RUB
447,2024-11-25 21:00:00,0,0.60,14.0,400.0,6500.0,1000.0,5000000.0,-,0.035,UZS
448,2024-11-25 21:00:00,38,0.50,24.0,800.0,4500.0,21000.0,32700000.0,-,0.035,GHS
449,2024-11-25 21:00:00,14,0.50,22.0,500.0,5000.0,1000.0,18900000.0,-,0.045,BRL
450,2024-11-25 21:00:00,44,0.75,12.0,800.0,8500.0,11000.0,36200000.0,-,0.040,PEN